import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import './Styles/index.css';
import Image from 'next/image';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div className="Header mx-auto rounded-b-3xl bg-opacity-50">
          <div className="flex justify-between items-center w-full">
            <div className="nav flex gap-[150px]">
              <a href=""><div>Home</div></a>

              <a href=""><div>Recent Work</div></a>

              <a href=""><div>Get In Touch</div></a>
            </div>

            <div className="flex space-x-5">
              <Image src="/fi-xnsuxx-linkedin.png" alt="Logo" width={25} height={25} />
              <Image src="/fi-xnsuxx-linkedin.png" alt="Logo" width={25} height={25} />
              <Image src="/fi-xnsuxx-linkedin.png" alt="Logo" width={25} height={25} />
            </div>
          </div>

        </div>



        {children}
        
        <div>
          This gonna be footer
        </div>
      </body>
    </html>
  );
}
